// Unit 2 training content lives here. Add, remove, or rewrite slides without
// touching simulator physics or UI code. `mechanics` describes what the sim is
// calculating behind the panel, so training teaches understanding as well as operation.
export type TutorialSlide = {
  title: string;
  system: string;
  text: string;
  action?: string;
  why?: string;
  watch?: string[];
  mechanics?: string[];
};
export type TutorialLevel = { title: string; objective: string; slides: TutorialSlide[] };

export const TUTORIAL_LEVELS: TutorialLevel[] = [
  {
    title: "Electrical essentials", objective: "Route power to Bus A, Bus S and DC Bus", slides: [
      { title: "Power before process", system: "Electrical", text: "Every pump, panel, lamp, and control needs an energized bus. Before the turbine is available, the external switchyard feeds the Startup Transformer, which can supply Bus A.", why: "A correctly selected pump cannot run if its bus has no source. Establish electrical availability before diagnosing a process-system fault.", mechanics: ["The simulator traces a power source through each closed breaker; a green bus is energized only when that full route exists.", "Each connected machine adds its kW demand to its assigned bus. A breaker position alone does not create power."], action: "Open Electrical and follow the route from External Switchyard to Startup Transformer to Bus A.", watch: ["Green bus indications mean energized.", "A closed breaker is not necessarily an energized bus.", "A bus can overload and trip when connected demand exceeds capacity."] },
      { title: "Safety, DC, and control power", system: "Electrical", text: "Route Bus A through the Bus A → Bus S breaker. From Safety Bus S, route power to the DC bus. Bus S also supports essential equipment; Bus E and the battery preserve control-room capability when normal sources are unavailable.", why: "The plant deliberately separates normal process loads from essential safety and control loads, so losing one path does not automatically remove every capability.", mechanics: ["Bus S is evaluated separately from Bus A; if its source is lost, its emergency loads cannot operate even if their own switches are ON.", "The DC and Bus E paths control illumination, panels, annunciators, and battery-backed functions. Dark or unresponsive controls usually mean a power route is missing."], action: "Turn on Startup Transformer, Bus A → Bus S, then Bus S → DC. Trace each newly energized block.", watch: ["Bus A feeds Safety Bus S.", "Bus S feeds DC and supports Bus E/battery charging.", "Essential cooling and emergency systems depend on Safety Bus S."] },
      { title: "Read availability, not switch position", system: "Overview", text: "A machine can be selected ON yet remain stopped because its bus is dead or power-locked by an overload. The electrical monitors show source, load, capacity, and machine availability together.", why: "An operator commands equipment, but electrical interlocks determine whether it can actually respond.", mechanics: ["The simulator recomputes bus demand continuously as pump flows and breakers change.", "Training Mode protects early lessons from overload trips; Advanced Mode uses normal limits."], action: "Ensure Bus A, Bus S, and DC Bus are available before continuing." },
    ]
  },
  {
    title: "Protection and annunciators", objective: "Confirm all RPS trip nodes are clear.", slides: [
      { title: "RPS is always watching", system: "RPS", text: "The Reactor Protection System monitors reactor level, pressure, core temperature, and reactor period. A dangerous value activates a trip node; depending on the condition, the reactor may trip or SCRAM.", why: "RPS watches relationships an operator can miss while occupied elsewhere. It acts quickly when ordinary control is no longer enough to keep the plant safe.", mechanics: ["Each simulation tick compares live process values with protective limits. A latched trip remains present until its cause is safe and a reset is valid.", "Reactor period measures the rate at which power changes, not simply current APRM."], action: "Open RPS and read the Channel A / Channel B status." },
      { title: "What an annunciator means", system: "Annunciators", text: "An annunciator is driven by a sensor condition, not by an operator's button press. A new alarm flashes and sounds; Silence stops its local audible signal, while Acknowledge records that it was seen.", why: "Separating alarm response from corrective action prevents a quiet alarm being mistaken for a solved problem.", mechanics: ["An active, unacknowledged alarm remains visually active after silence. When its sensor clears before acknowledgement, it flashes slowly until acknowledged.", "Blue windows are advisory status lamps: steady, silent indications that a system is active."], action: "Locate the local Silence and Acknowledge controls, then verify no critical alarm is active.", watch: ["Silence does not clear the initiating condition.", "Acknowledging does not reset a trip.", "Only correct the process cause, then reset when permitted."] },
      { title: "A safe starting point", system: "RPS", text: "Before adding reactivity or running equipment, confirm every RPS node is clear. If a node remains active, identify its cause instead of repeatedly pressing reset.", why: "A valid reset confirms the plant has returned to a safe state; it is not a bypass for a live unsafe condition.", mechanics: ["The simulator prevents restart paths while relevant protective conditions remain present.", "Low thermal power by itself is not a reactor trip condition: protection responds to unsafe rates and limits."], action: "Continue once all RPS nodes read CLEAR." },
    ]
  },
  {
    title: "How the reactor responds", objective: "Identify C3 and explain the difference between APRM and reactor period.", slides: [
      { title: "The chain reaction", system: "Control rods", text: "Fission releases heat and neutrons. Some neutrons cause later fissions, which sustains the chain reaction. Control rods are neutron absorbers: inserting them captures more neutrons; withdrawing them leaves more available for fission.", why: "This is the first cause in every plant response: more reactivity creates more heat, then more steam, pressure, turbine flow, condenser load, and water movement.", mechanics: ["Each of the 36 simulated rods has its own insertion position. The reactor calculates rod reactivity from the combined withdrawal of every rod.", "The panel displays withdrawal: 0% withdrawn is fully inserted and 100% withdrawn is fully out. Internally, the drive model stores the inverse insertion value."], action: "Open Control Rods, select C3, and read both its withdrawn value and AVG WITHDRAWN." },
      { title: "The core is a pattern, not one slider", system: "Control rods", text: "Withdrawing one rod creates a local reactivity change. Moving rods in a balanced centre-out pattern spreads that change through the core and avoids concentrating it in one convenient location.", why: "Core geometry matters. The rod map shows individual drives so you can see that selected, group, and all commands still act through real rods.", mechanics: ["The map colour, selected-rod reading, average position, temperature, and APRM contribution originate from the same rod array.", "GROUP and ALL only send a command to more rods; they do not ignore startup order or withdrawal blocks."], action: "Select a few rods and observe that only the selected ring changes; do not withdraw a rod yet." },
      { title: "APRM: how much power", system: "Control rods", text: "APRM is the average reactor power indication. It shows how much thermal power is the reactor producing right now. In Unit 2 it is calculated from rod reactivity plus recirculation contribution, then limited by protection.", why: "APRM is the number you use to plan heat, steam, and turbine loading, so learning its behavior can improve operations heavily.", mechanics: ["Rods provide the main share of available APRM. The two recirculation pumps provide the remaining operating margin when conditions allow.", "APRM affects reactor heat and steam production gradually; it is not an instantaneous turbine-output setting."], action: "Find APRM on the panel and compare it with the all-inserted rod map." },
      { title: "Reactor period: how fast it is changing", system: "Control rods", text: "Reactor period is not another power meter. It describes the power trend—the time scale of a rise or fall. A moderate APRM can still have a concerningly short period if reactivity is being added too fast.", why: "Use APRM to judge level and period to judge aggression. The safe habit is a small change followed by time to observe its response.", mechanics: ["The simulator filters the period calculation so it represents the sustained reactivity trend rather than display noise.", "Rod movement and recirculation change period through reactivity. Their rate effects are deliberately different, so a fast recirculation command does not create an instant period trip."], action: "Read the PERIOD meter. In the next lesson you will make a small change and watch it settle." },
      { title: "Rods and recirculation have different jobs", system: "Control rods", text: "Rods make deliberate reactivity changes. Recirculation changes coolant flow and the core's moderation/void behaviour, making it better for normal fine trim once the plant is operating.", why: "Knowing which tool to use avoids relying on expensive recirculation at startup or making unnecessary rod movements at power.", mechanics: ["Each recirculation pump has actual flow, electrical demand, cavitation checks, and a separately filtered contribution to APRM.", "Auto APRM can operate rods or recirculation using gradual real commands. It never edits APRM directly."], action: "Do not operate controls yet; continue after you can explain why APRM and period are different." },
    ]
  },
  {
    title: "Rod startup programme", objective: "Make one valid SRM withdrawal of the selected C3 rod.", slides: [
      { title: "Why startup is staged", system: "Control rods", text: "Near criticality, a reactor is sensitive to small reactivity additions. Unit 2 uses SRM and IRM startup ranges instead of allowing every rod to be withdrawn freely from shutdown.", why: "Staging gives the operator time to observe response after each small change and prevents a large, poorly distributed reactivity addition.", mechanics: ["SRM provides source-range count feedback at the earliest stage. IRM follows with intermediate-range progression; RUN is normal power-range operation.", "The next permitted rod is calculated from a centre-out program. Its amber blink identifies the rod currently allowed next."], action: "Find the blinking next-permitted rod. It is C3 at the beginning of this lesson." },
      { title: "SRM: first controlled motion", system: "Control rods", text: "SRM is the first startup range. Select the permitted rod, choose ROD scope, move the drive toward WITHDRAW, and observe source-range count and rod position. This simulator's SRM cycle stops at 5% withdrawn.", why: "The small first motion proves the drive works and lets the operator see a gradual core response before more reactivity is allowed.", mechanics: ["The SRM block compares the selected rod with the programmed next rod and the 5% cycle limit. A refused command produces the block indication rather than moving the rod.", "Standard manual startup movement is deliberately slow: roughly 3.5 seconds for 5% withdrawal. Holding the drive does not teleport a rod."], action: "Keep C3 selected, choose ROD scope, and withdraw it slightly.", watch: ["A block buzzer means check rod order, mode, and cycle limit.", "INSERT is the conservative direction and reduces reactivity."] },
      { title: "IRM: watch the intermediate range", system: "Control rods", text: "After SRM, IRM uses the Intermediate Range Monitor. Its eight selectable ranges, R1 through R8, let the operator read very low and progressively higher power without losing resolution. Use the IRM range lever to choose a range at any time.", why: "Changing an IRM range changes the measurement scale, not reactor reactivity. The rods still follow the programmed centre-out withdrawal sequence.", mechanics: ["The IRM meter uses the configured conversion: 10^((range − 6) / 2) × (position / 50). At a 50/100 position, R1–R8 correspond to roughly 0.003%, 0.01%, 0.03%, 0.1%, 0.3%, 1%, 3%, and 10% APRM.", "The display flags readings below 0.2% as approximate because the U2 APRM display is not accurate in that region. The selected IRM range never directly changes rods or APRM."], action: "Use the IRM range lever to inspect R1–R8, then continue withdrawing only the blinking permitted rod." },
      { title: "RUN is not a shortcut", system: "Control rods", text: "RUN is selected after the startup programme is complete and APRM is above the RUN threshold. It removes startup group blocks, but it does not make large rod movements safe.", why: "The startup rules are there to approach power predictably. RUN changes the permitted control range, not the reactor physics.", mechanics: ["At operating power, recirculation is usually the finer tool for APRM trim; rods remain the stronger reactivity control.", "Short insert/withdraw pulses let APRM and reactor period settle between commands."], action: "Complete the small valid SRM movement to finish this level." },
    ]
  },
  {
    title: "Turbine steam and condenser", objective: "Bring main steam pressure near 7,100 kPa.", slides: [
      { title: "Controlled reactor power", system: "Turbine", text: "For this lesson, Auto APRM provides a controlled 20% training startup. The manual SRM/IRM progression remains the normal reactor startup route.", why: "Holding power lets you learn steam routing without repeating the full rod programme.", mechanics: ["The training hold supplies the APRM used by the steam model; it does not bypass real pressure, valve, condenser, or electrical behaviour."], action: "Observe the fixed 20% APRM indication." },
      { title: "Steam pressure is a balance", system: "Turbine", text: "Reactor power produces steam. Pressure rises when production exceeds steam leaving through the main valve, bypass, and relief valves. The main valve feeds the turbine; bypass sends steam directly to the condenser.", why: "Pressure is stored energy. Turbine speed responds to admitted steam flow, not just a valve percentage.", mechanics: ["Total steam outflow is main-valve flow plus bypass flow. Both paths affect pressure and condenser load, but only main admission produces turbine work."], action: "Build pressure toward 7,100 kPa before admitting substantial turbine steam." },
      { title: "Condenser is the low-pressure end", system: "Condenser", text: "A healthy condenser operates around 40–70 mbar, with best efficiency near 52 mbar. It condenses exhaust steam back into water so the cycle can continue.", why: "Poor vacuum reduces turbine efficiency and makes it harder for steam to leave the turbine.", mechanics: ["Condenser pressure responds to steam load, condenser-valve position, air removal, and circulation. Its efficiency peaks near target pressure rather than at a fixed valve setting."], action: "Bring condenser pressure into its normal band." },
      { title: "Use automatic pressure control", system: "Turbine", text: "Turbine pressure auto uses bypass and main admission to hold approximately 7,100 kPa. It prefers avoiding bypass once the turbine can accept steam, using it for faster pressure correction.", why: "This gives the turbine room to take more load while preventing uncontrolled pressure rise.", mechanics: ["The controller changes real valve settings in bounded steps and reacts continuously to pressure and pressure-rate trend."], action: "Stabilize main steam pressure near 7,100 kPa." },
    ]
  },
  {
    title: "Turbine run-up", objective: "Stabilize turbine speed at 3000 RPM.", slides: [
      { title: "Preparation protects the machine", system: "Turbine", text: "Before run-up, the turbine needs acceptable steam conditions, condenser vacuum, hydraulic pressure, lubrication, turning-gear status, and oil condition. Advanced Mode exposes the full checklist.", why: "Steam can spin a turbine quickly, but bearing and hydraulic systems protect it while it does so.", mechanics: ["The simulator evaluates preparation status continuously. Some bad conditions increase trip risk at high RPM; synchronization requires all required conditions."], action: "Review the run-up checklist before applying Auto RPM." },
      { title: "Use Auto RPM", system: "Turbine", text: "Auto RPM balances main admission and bypass while approaching 3,000 RPM. Near nominal speed it reduces corrections to hold island frequency steadily.", why: "A stable approach makes synchronization practical and gives time to identify an abnormal pressure or vacuum trend.", mechanics: ["Auto RPM predicts speed/pressure movement, makes bounded valve changes, and settles when stable. It controls actual valves, never directly sets RPM."], action: "Reach 2,800 RPM or more." },
      { title: "Steam flow becomes output", system: "Turbine", text: "After the generator is excited and connected, increased admitted steam flow creates more generator output. The reactor, turbine, condenser, MCC, and grid then influence each other.", why: "A valve change is no longer just a speed change—it changes load, pressure, steam flow, and water inventory together.", mechanics: ["At 100% APRM, normal operation is calibrated toward about 1,200 MW of reactor output; generator delivery depends on steam admission and condenser efficiency."], action: "Continue once stable turbine speed is reached." },
    ]
  },
  {
    title: "MCC flow balance", objective: "Run MCC circulation, condensate, and feedwater together.", slides: [
      { title: "One closed water loop", system: "MCC", text: "The cooling path is Reactor → Turbine/Condenser → Hotwell → Condensate Pumps → Deaerator → Feedwater Pumps → Reactor. Steam flow is set by the turbine operator; MCC balances water around it.", why: "The three flow meters show the same mass of water at different locations, not three independent supplies.", mechanics: ["Steam flow removes reactor inventory into the condenser/hotwell path. Condensate moves Hotwell to DA; feedwater moves DA to Reactor. Each level derives from inflow minus outflow."], action: "Open MCC and compare all three flow meters." },
      { title: "Levels are consequences", system: "MCC", text: "A level rises when inflow exceeds outflow and falls when outflow exceeds inflow. If Hotwell is high while DA is low, condensate should temporarily exceed feedwater. If reactor is low, feedwater must exceed steam until it recovers.", why: "Good MCC control balances real flows instead of directly chasing one level display.", mechanics: ["Inventory change is rate-limited for readable plant response. MCC Auto moves real pump commands to match steam flow and correct level error; it never edits a vessel level directly."], action: "Enable MCC circulation before expecting normal process-level movement." },
      { title: "Make a stable loop", system: "MCC", text: "Start condensate and feedwater, then adjust them toward current steam flow. The DA conditions feedwater but does not change the basic mass-balance rule.", why: "When flows match, levels stop drifting. Small planned differences are useful only while recovering inventory.", mechanics: ["Each feedwater pump is rated up to 2,000 kg/s. Electrical availability and pump selection still limit which commanded flow can actually be delivered."], action: "Run MCC circulation, condensate, and feedwater together." },
    ]
  },
  {
    title: "Grid connection and integration", objective: "Synchronize the generator to the grid.", slides: [
      { title: "Synchronizing", system: "Turbine + electrical", text: "The generator must be near 3,000 RPM before closing the grid breaker. The synchronoscope and lamps show phase agreement; use them rather than closing on a guessed speed.", why: "Connecting AC sources at the wrong frequency or phase imposes a severe mechanical and electrical shock.", mechanics: ["Synchronoscope rotation comes from generator/grid frequency difference. Unit 2 permits closure only in its tight ±5 RPM synchronization range."], action: "Use Auto RPM or manual valves to enter the sync range." },
      { title: "Auxiliary buses", system: "Electrical", text: "Once synchronized—or held in island range—the turbine can energize Bus A and Bus B through their turbine-fed breakers. Their loads are real and can overload a bus outside Training Mode.", why: "As the unit becomes self-powered, generation, auxiliary load, and grid demand must remain balanced.", mechanics: ["When both turbine-fed buses are available, their demand shares turbine supply capacity. The electrical panel evaluates total demand rather than treating both buses as unlimited."], action: "Check bus demand before closing turbine-fed breakers." },
      { title: "Connect carefully", system: "Electrical", text: "Close exciter and grid breaker only with stable turbine conditions. After connection, generator output follows admitted steam flow and the unit becomes a coupled reactor, turbine, condenser, MCC, and grid system.", why: "This is where every previous system starts influencing every other one.", mechanics: ["Grid demand changes over time. Staying close to demand earns points, while automatic systems reduce that earning rate after their cooldown rules."], action: "Synchronize the generator to complete training, then exit Training Mode for unrestricted operation." },
    ]
  },
];
