import { useEffect, useRef, useState } from "react";
import { Zap } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MaintainedSwitch, ModeSelector, SpringLever } from "@/components/HardwareControls";
import { AUTO_ROD_RATES, AutoSpeed, ControlRod, cycleLimit, getIrmEquivalentAprm, ReactorMode, RodSelectionScope } from "@/lib/rodProgram";

interface Props { rods: ControlRod[]; selectedRodId: string; mode: ReactorMode; irmRange: number; startupCycle: number; aprm: number; rodAprm?: number; srmCount: number; direction: number; autoEnabled: boolean; autoTarget: number; autoSpeed: AutoSpeed; autoMode: "rods" | "recirculation"; autoMessage: string; nextRodId?: string; selectionScope: RodSelectionScope; reactorPeriod: number; recirculationAprm?: number; recircPumpA?: boolean; recircPumpB?: boolean; recircSpeedA?: number; recircSpeedB?: number; recircAFlow?: number; recircBFlow?: number; onRecircPumpAChange?: (value: boolean) => void; onRecircPumpBChange?: (value: boolean) => void; onRecircSpeedAChange?: (value: number) => void; onRecircSpeedBChange?: (value: number) => void; onSelectRod: (id: string) => void; onModeChange: (mode: ReactorMode) => void; onDirectionChange: (direction: number) => void; onIrmRangeChange: (value: number) => void; onAdvanceStartupCycle: () => void; onAutoEnabledChange: (enabled: boolean) => void; onAutoTargetChange: (target: number) => void; onAutoSpeedChange: (speed: AutoSpeed) => void; onAutoModeChange: (mode: "rods" | "recirculation") => void; onSelectionScopeChange: (scope: RodSelectionScope) => void; }

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
const formatPower = (value: number) => value < .01 ? value.toFixed(4) : value.toFixed(3);

const FlowControl = ({ label, value, disabled, onChange }: { label: string; value: number; disabled?: boolean; onChange: (value: number) => void }) => {
  const [direction, setDirection] = useState(0);
  const valueRef = useRef(value); const changeRef = useRef(onChange);
  useEffect(() => { valueRef.current = value; }, [value]);
  useEffect(() => { changeRef.current = onChange; }, [onChange]);
  useEffect(() => { if (!direction) return; const timer = window.setInterval(() => changeRef.current(Math.round(clamp(valueRef.current + direction * .1, 0, 100) * 10) / 10), 250); return () => window.clearInterval(timer); }, [direction]);
  return <div className={disabled ? "pointer-events-none opacity-40" : undefined}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value.toFixed(1)}%</strong></div><SpringLever label={`${label} CONTROL`} negativeLabel="LOWER" positiveLabel="RAISE" extended direction={direction} onDirectionChange={setDirection}/></div>;
};

export const ControlRodsPanel = (props: Props) => {
  const selected = props.rods.find((rod) => rod.id === props.selectedRodId) ?? props.rods[0];
  const physicalAverageWithdrawn = props.rods.reduce((sum, rod) => sum + 100 - rod.position, 0) / props.rods.length;
  const rangeAtFifty = Math.pow(10, (clamp(props.irmRange, 1, 8) - 6) / 2);
  // IRM is a scaled indication of total reactor power, including the
  // recirculation contribution. It remains read-only: changing range cannot
  // feed back into APRM or rod reactivity.
  const irmPosition = clamp(props.aprm / rangeAtFifty * 50, 0, 100);
  const irmAprm = getIrmEquivalentAprm(props.irmRange, irmPosition);
  const withdrawalLimit = 100 - cycleLimit(props.mode, props.startupCycle);
  const [irmDirection, setIrmDirection] = useState(0); const resetTimer = useRef<number | null>(null);
  const changeIrmRange = (direction: number) => { if (!direction) return; if (resetTimer.current) window.clearTimeout(resetTimer.current); setIrmDirection(direction); props.onIrmRangeChange(clamp(props.irmRange + Math.sign(direction), 1, 8)); resetTimer.current = window.setTimeout(() => setIrmDirection(0), 220); };
  useEffect(() => () => { if (resetTimer.current) window.clearTimeout(resetTimer.current); }, []);
  return <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
    <Card className="border-emerald-500/30 bg-slate-900/70"><CardHeader><CardTitle className="flex gap-2 text-emerald-300"><Zap />Control Rod Map</CardTitle></CardHeader><CardContent>
      <div className="mb-4 flex items-center justify-between"><div><span className="text-xs text-slate-400">SELECTED</span><div className="text-2xl font-black">{selected.id} <span className="text-sm font-normal text-slate-400">{(100 - selected.position).toFixed(1)}% withdrawn</span></div></div><Badge className={props.mode === "SD" ? "bg-red-700" : "bg-amber-500 text-slate-950"}>{props.mode === "IPR" ? "IRM" : props.mode}</Badge></div>
      <div className="mx-auto max-w-lg rounded-[42%] border-8 border-slate-700 bg-gradient-to-br from-slate-700 via-slate-900 to-slate-950 p-5 shadow-inner sm:p-10"><div className="grid grid-cols-6 gap-1.5 rounded-lg border border-slate-600 bg-slate-950 p-2 sm:gap-2 sm:p-3">{props.rods.map((rod) => { const withdrawn = 100 - rod.position; const active = rod.id === props.selectedRodId; const next = props.mode !== "RUN" && rod.id === props.nextRodId; return <button key={rod.id} onClick={() => props.onSelectRod(rod.id)} className={`aspect-square min-h-8 rounded border text-[10px] font-black touch-manipulation sm:min-h-10 ${active ? "border-white ring-2 ring-cyan-400" : next ? "animate-pulse border-amber-200 ring-2 ring-amber-400" : "border-slate-700"}`} style={{ backgroundColor: `hsl(${120 - withdrawn * 1.15} 70% ${18 + withdrawn * .18}%)` }}>{rod.id}</button>; })}</div></div>
      <div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><div className="rounded bg-slate-950 p-3"><small>ROD TEMP</small><br/>{selected.temperature.toFixed(0)}°C</div><div className="rounded bg-slate-950 p-3"><small>GROUP</small><br/>{selected.group}</div><div className="rounded bg-slate-950 p-3"><small>AVG WITHDRAWN</small><br/>{physicalAverageWithdrawn.toFixed(2)}%</div><div className="rounded bg-slate-950 p-3"><small>PERIOD</small><br/>{props.reactorPeriod >= 999 ? "∞" : `${props.reactorPeriod.toFixed(1)} s`}</div></div>
    </CardContent></Card>
    <div className="space-y-6">
      <Card className="border-amber-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-amber-200">Startup / Rod Drive</CardTitle></CardHeader><CardContent className="space-y-4">
        <ModeSelector value={props.mode} onChange={props.onModeChange}/>
        <div className="grid grid-cols-2 gap-2 rounded bg-slate-950 p-3 text-sm sm:grid-cols-5"><div><small>SRM</small><br/>{props.srmCount.toFixed(0)} CPS</div><div><small>APRM</small><br/>{formatPower(props.aprm)}%</div><div><small>MAX WITHDRAWN</small><br/>{withdrawalLimit.toFixed(0)}%</div><div><small>STARTUP CYCLE</small><br/>{props.mode === "IPR" ? `${props.startupCycle}/8` : "—"}</div><div><small>IRM RANGE</small><br/>R{props.irmRange}</div></div>
        <div className="rounded border border-cyan-400/40 bg-cyan-950/20 p-3"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><p className="text-[10px] font-black tracking-[.16em] text-cyan-200">INTERMEDIATE RANGE MONITOR</p><strong className="text-2xl text-cyan-100">R{props.irmRange} · {irmPosition.toFixed(2)}/100</strong></div><div className="text-right"><p className="text-[10px] text-slate-400">IRM → APRM</p><strong className="text-lg text-emerald-300">{formatPower(irmAprm)}% APRM</strong></div></div><div className="mt-3 h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-cyan-400 transition-all" style={{ width: `${irmPosition}%` }}/></div><p className="mt-2 text-[10px] leading-4 text-slate-400">Delayed flux indication: at R1, 50% equals 0.003% APRM; at R8, 50% equals 10% APRM. The active range applies its own scale.</p></div>
        <SpringLever label="IRM RANGE SELECTOR" negativeLabel="LOWER RANGE" positiveLabel="RAISE RANGE" direction={irmDirection} onDirectionChange={changeIrmRange} hideNeutral tooltip="Select + or − to change one active IRM range. It returns automatically; the active range defines the IRM-to-APRM scale."/>
        {props.mode === "IPR" && <button onClick={props.onAdvanceStartupCycle} className="w-full rounded border border-amber-400/60 bg-amber-500/10 py-2 text-xs font-black text-amber-100">ADVANCE STARTUP CYCLE ({props.startupCycle}/8)</button>}
        <div className="grid grid-cols-3 gap-2">{(["rod", "group", "all"] as RodSelectionScope[]).map((scope) => <button key={scope} onClick={() => props.onSelectionScopeChange(scope)} className={`rounded border py-2 text-xs font-bold ${scope === props.selectionScope ? "border-cyan-300 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{scope.toUpperCase()}</button>)}</div>
        <SpringLever label={`${props.selectionScope.toUpperCase()} DRIVE`} negativeLabel="WITHDRAW" positiveLabel="INSERT" direction={props.direction} onDirectionChange={props.onDirectionChange}/>
      </CardContent></Card>
      <Card className="border-blue-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-blue-200">Recirculation flow</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex justify-between rounded bg-slate-950 p-3 text-sm"><span>RECIRCULATION APRM</span><strong className="text-cyan-300">{(props.recirculationAprm ?? 0).toFixed(1)}%</strong></div><div className="grid grid-cols-2 gap-3">{[["PUMP A FLOW", props.recircAFlow ?? 0], ["PUMP B FLOW", props.recircBFlow ?? 0]].map(([label, flow]) => <div key={String(label)} className="rounded border border-sky-500/30 bg-slate-950 p-3"><div className="flex justify-between text-[10px] text-slate-400"><span>{label}</span><span>0–2000</span></div><strong className="mt-1 block text-xl text-cyan-300">{Number(flow).toFixed(1)} <small className="text-xs">kg/s</small></strong></div>)}</div><div className="grid grid-cols-2 gap-3"><MaintainedSwitch label="RECIRC PUMP A" on={props.recircPumpA ?? false} onChange={(value) => props.onRecircPumpAChange?.(value)}/><MaintainedSwitch label="RECIRC PUMP B" on={props.recircPumpB ?? false} onChange={(value) => props.onRecircPumpBChange?.(value)}/></div><FlowControl label="PUMP A SPEED" value={props.recircSpeedA ?? 0} disabled={!props.recircPumpA} onChange={(value) => props.onRecircSpeedAChange?.(value)}/><FlowControl label="PUMP B SPEED" value={props.recircSpeedB ?? 0} disabled={!props.recircPumpB} onChange={(value) => props.onRecircSpeedBChange?.(value)}/></CardContent></Card>
      <Card className="border-cyan-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-cyan-200">Manual / Auto APRM Speed</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-2"><button onClick={() => props.onAutoModeChange("rods")} className={`rounded border py-3 text-xs font-black ${props.autoMode === "rods" ? "border-cyan-200 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>ROD DRIVE</button><button onClick={() => props.onAutoModeChange("recirculation")} className={`rounded border py-3 text-xs font-black ${props.autoMode === "recirculation" ? "border-cyan-200 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>RECIRCULATION</button></div><div className="grid grid-cols-3 gap-2">{(["slow", "medium", "fast"] as AutoSpeed[]).map((speed) => <button key={speed} onClick={() => props.onAutoSpeedChange(speed)} className={`rounded border py-2 text-xs ${props.autoSpeed === speed ? "border-cyan-300 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{speed.toUpperCase()}<small className="block">AUTO {AUTO_ROD_RATES[speed]}%/s</small></button>)}</div><div className="flex justify-between"><span>Auto target</span><input className="w-20 rounded bg-slate-950 px-2 text-right" type="number" min="0" max="100" step="0.1" value={props.autoTarget} onChange={(event) => props.onAutoTargetChange(Number(event.target.value))}/><span>%</span></div><button onClick={() => props.onAutoEnabledChange(!props.autoEnabled)} className={`w-full rounded border py-3 text-sm font-black ${props.autoEnabled ? "border-emerald-200 bg-emerald-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{props.autoEnabled ? "AUTO ENGAGED" : "ENGAGE AUTO"}</button><p className="rounded bg-slate-950 p-3 text-xs text-slate-400">{props.autoMessage}</p></CardContent></Card>
    </div>
  </div>;
};
