import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { MaintainedSwitch, ModeSelector, SpringLever } from "@/components/HardwareControls";
import { AUTO_ROD_RATES, AutoSpeed, ControlRod, cycleLimit, ReactorMode, RodSelectionScope } from "@/lib/rodProgram";
import { Zap } from "lucide-react";

interface Props { rods: ControlRod[]; selectedRodId: string; mode: ReactorMode; iprCycle: number; aprm: number; srmCount: number; direction: number; autoEnabled: boolean; autoTarget: number; autoSpeed: AutoSpeed; autoMessage: string; nextRodId?: string; selectionScope: RodSelectionScope; reactorPeriod: number; recirculationAprm?: number; recircPumpA?: boolean; recircPumpB?: boolean; recircSpeedA?: number; recircSpeedB?: number; recircADirection?: number; recircBDirection?: number; onRecircPumpAChange?: (value: boolean) => void; onRecircPumpBChange?: (value: boolean) => void; onRecircSpeedAChange?: (value: number) => void; onRecircSpeedBChange?: (value: number) => void; onRecircADirectionChange?: (value: number) => void; onRecircBDirectionChange?: (value: number) => void; onSelectRod: (id: string) => void; onModeChange: (mode: ReactorMode) => void; onDirectionChange: (direction: number) => void; onAdvanceCycle: () => void; onAutoEnabledChange: (enabled: boolean) => void; onAutoTargetChange: (target: number) => void; onAutoSpeedChange: (speed: AutoSpeed) => void; onSelectionScopeChange: (scope: RodSelectionScope) => void; }

const Slider = ({ value, disabled, onValueChange }: { value: number[]; max: number; disabled?: boolean; onValueChange: (value: number[]) => void }) => {
  const [direction, setDirection] = useState(0);
  // The pump controller responds promptly, while the reactor-period model applies
  // its own slow filter to the resulting APRM change in ReactorSimulator.
  useEffect(() => { const tick = window.setInterval(() => { if (direction) onValueChange([Math.max(0, Math.min(100, value[0] + direction * 5))]); }, 250); return () => window.clearInterval(tick); }, [direction, value, onValueChange]);
  return <div className={disabled ? "pointer-events-none opacity-40" : undefined}><SpringLever label="RECIRC FLOW CONTROL" negativeLabel="LOWER" positiveLabel="RAISE" direction={direction} onDirectionChange={setDirection}/></div>;
};

export const ControlRodsPanel = (props: Props) => {
  const selected = props.rods.find(rod => rod.id === props.selectedRodId) ?? props.rods[0];
  const average = props.rods.reduce((sum, rod) => sum + rod.position, 0) / props.rods.length;
  const limit = cycleLimit(props.mode, props.iprCycle);
  return <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
    <Card className="border-emerald-500/30 bg-slate-900/70"><CardHeader><CardTitle className="flex gap-2 text-emerald-300"><Zap />Control Rod Map</CardTitle></CardHeader><CardContent><div className="mb-4 flex items-center justify-between"><div><span className="text-xs text-slate-400">SELECTED</span><div className="text-2xl font-black">{selected.id} <span className="text-sm font-normal text-slate-400">{selected.position.toFixed(1)}% inserted</span></div></div><Badge className={props.mode === "SD" ? "bg-red-700" : "bg-amber-500 text-slate-950"}>{props.mode}</Badge></div><div className="mx-auto max-w-lg rounded-[42%] border-8 border-slate-700 bg-gradient-to-br from-slate-700 via-slate-900 to-slate-950 p-5 shadow-inner sm:p-10"><div className="grid grid-cols-6 gap-1.5 rounded-lg border border-slate-600 bg-slate-950 p-2 sm:gap-2 sm:p-3">{props.rods.map(rod => { const withdrawn = 100 - rod.position; const active = rod.id === props.selectedRodId; const next = props.mode !== "RUN" && rod.id === props.nextRodId; return <button key={rod.id} onClick={() => props.onSelectRod(rod.id)} className={`aspect-square min-h-8 rounded border text-[10px] font-black touch-manipulation sm:min-h-10 ${active ? "border-white ring-2 ring-cyan-400" : next ? "animate-pulse border-amber-200 ring-2 ring-amber-400" : "border-slate-700"}`} style={{ backgroundColor: `hsl(${120 - withdrawn * 1.15} 70% ${18 + withdrawn * .18}%)` }}>{rod.id}</button>; })}</div></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><div className="rounded bg-slate-950 p-3"><small>ROD TEMP</small><br/>{selected.temperature.toFixed(0)}°C</div><div className="rounded bg-slate-950 p-3"><small>GROUP</small><br/>{selected.group}</div><div className="rounded bg-slate-950 p-3"><small>AVG POS</small><br/>{average.toFixed(2)}%</div><div className="rounded bg-slate-950 p-3"><small>PERIOD</small><br/>{props.reactorPeriod >= 999 ? "∞" : `${props.reactorPeriod.toFixed(1)} s`}</div></div></CardContent></Card>
    <div className="space-y-6"><Card className="border-amber-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-amber-200">Startup / Rod Drive</CardTitle></CardHeader><CardContent className="space-y-4"><ModeSelector value={props.mode} onChange={props.onModeChange}/><div className="grid grid-cols-3 gap-2 rounded bg-slate-950 p-3 text-sm"><div><small>SRM</small><br/>{props.srmCount.toFixed(0)} CPS</div><div><small>APRM</small><br/>{props.aprm.toFixed(3)}%</div><div><small>BLOCK</small><br/>{limit.toFixed(0)}% INS.</div></div><div className="rounded border border-slate-700 p-3"><div className="flex justify-between text-xs"><span>{props.mode === "SRM" ? "SRM CYCLE 1 / 1" : `IPR CYCLE ${props.iprCycle} / 3`}</span><span>{props.mode === "SRM" ? "5% withdrawal" : "5% per cycle"}</span></div><button onClick={props.onAdvanceCycle} disabled={props.mode !== "IPR" || props.iprCycle >= 3} className="mt-3 w-full rounded border border-amber-500/60 bg-amber-500/20 py-2 text-xs font-bold text-amber-200 disabled:opacity-40">ADVANCE IPR CYCLE</button></div><div className="grid grid-cols-3 gap-2">{(["rod", "group", "all"] as RodSelectionScope[]).map(scope => <button key={scope} onClick={() => props.onSelectionScopeChange(scope)} className={`rounded border py-2 text-xs font-bold ${scope === props.selectionScope ? "border-cyan-300 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{scope.toUpperCase()}</button>)}</div><SpringLever label={`${props.selectionScope.toUpperCase()} DRIVE`} negativeLabel="WITHDRAW" positiveLabel="INSERT" direction={props.direction} onDirectionChange={props.onDirectionChange}/></CardContent></Card>
      <Card className="border-blue-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-blue-200">Recirculation flow</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex justify-between rounded bg-slate-950 p-3 text-sm"><span>RECIRCULATION APRM</span><strong className="text-cyan-300">{(props.recirculationAprm ?? 0).toFixed(1)}%</strong></div><div className="grid grid-cols-2 gap-3"><MaintainedSwitch label="RECIRC PUMP A" on={props.recircPumpA ?? false} onChange={value => props.onRecircPumpAChange?.(value)}/><MaintainedSwitch label="RECIRC PUMP B" on={props.recircPumpB ?? false} onChange={value => props.onRecircPumpBChange?.(value)}/></div><div><div className="mb-1 flex justify-between text-xs"><span>PUMP A SPEED</span><strong>{props.recircSpeedA ?? 0}%</strong></div><Slider value={[props.recircSpeedA ?? 0]} max={100} disabled={!props.recircPumpA} onValueChange={value => props.onRecircSpeedAChange?.(value[0])}/></div><div><div className="mb-1 flex justify-between text-xs"><span>PUMP B SPEED</span><strong>{props.recircSpeedB ?? 0}%</strong></div><Slider value={[props.recircSpeedB ?? 0]} max={100} disabled={!props.recircPumpB} onValueChange={value => props.onRecircSpeedBChange?.(value[0])}/></div><p className="text-xs text-slate-400">Pump speed moves at 20%/s. Each pump provides up to 37.5 APRM points; the reactor-period calculation keeps its separate slow filter.</p></CardContent></Card><Card className="border-cyan-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-cyan-200">Manual / Auto APRM Speed</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-slate-400">Selects manual rod-drive multiplier and Auto APRM response profile.</p><div className="grid grid-cols-3 gap-2">{(["slow", "medium", "fast"] as AutoSpeed[]).map(speed => <button key={speed} onClick={() => props.onAutoSpeedChange(speed)} className={`rounded border py-2 text-xs ${props.autoSpeed === speed ? "border-cyan-300 bg-cyan-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{speed.toUpperCase()}<small className="block">MANUAL {speed === "slow" ? "0.5×" : speed === "fast" ? "2×" : "1×"}</small><small className="block">AUTO {AUTO_ROD_RATES[speed]}%/s</small></button>)}</div><div className="flex justify-between"><span>Auto target</span><input className="w-20 rounded bg-slate-950 px-2 text-right" type="number" min="0" max="100" step="0.1" value={props.autoTarget} onChange={event => props.onAutoTargetChange(Number(event.target.value))}/><span>%</span></div><button onClick={() => props.onAutoEnabledChange(!props.autoEnabled)} className={`w-full rounded border py-3 text-sm font-black ${props.autoEnabled ? "border-emerald-200 bg-emerald-500 text-slate-950" : "border-slate-600 bg-slate-950"}`}>{props.autoEnabled ? "AUTO ENGAGED" : "ENGAGE AUTO"}</button><p className="rounded bg-slate-950 p-3 text-xs text-slate-400">{props.autoMessage}</p></CardContent></Card></div>
  </div>;
};
