import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { MaintainedSwitch, SpringButton, SpringLever } from "@/components/HardwareControls";

type DiskState = "intact" | "ruptured" | "removed" | "replaced";
type Props = {
  pressure: number; temperature: number; intake: number; outtake: number; intakeFlow: number; outtakeFlow: number; intakeDirection: number; outtakeDirection: number; auto: boolean; fastCloseHeld: boolean;
  bypassOpen: boolean; mainAirValveOpen: boolean; disk: DiskState;
  onIntakeDirection: (value: number) => void; onOuttakeDirection: (value: number) => void; onAuto: (value: boolean) => void; onFastClose: (value: boolean) => void;
  onBypass: (value: boolean) => void; onMainAirValve: (value: boolean) => void; onRemoveDisk: () => void; onInstallDisk: () => void; onRestore: () => void;
};

export const DeaeratorHallPanel = (p: Props) => <div className="space-y-6">
  <Card className="border-amber-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-amber-200">Deaerator Hall — pressure and air controls</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid grid-cols-2 gap-3"><div className="rounded bg-slate-950 p-4 text-center"><small>DA PRESSURE</small><strong className={`block text-3xl ${p.pressure > 2.05 ? "text-red-300" : "text-emerald-300"}`}>{p.pressure.toFixed(2)} bar</strong></div><div className="rounded bg-slate-950 p-4 text-center"><small>DA TEMPERATURE</small><strong className="block text-3xl text-cyan-200">{p.temperature.toFixed(1)} °C</strong></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded border border-cyan-500/30 bg-slate-950 p-3 text-center"><small>DA INTAKE AIR FLOW</small><strong className="block text-2xl text-cyan-200">{p.intakeFlow.toFixed(2)} kg/s</strong><span className="text-xs text-slate-400">maximum 10 kg/s · follows MCC flow</span></div><div className="rounded border border-cyan-500/30 bg-slate-950 p-3 text-center"><small>DA OUTTAKE AIR FLOW</small><strong className="block text-2xl text-cyan-200">{p.outtakeFlow.toFixed(2)} kg/s</strong><span className="text-xs text-slate-400">maximum 20 kg/s · exhaust flow</span></div></div><MaintainedSwitch label="DA AUTO" on={p.auto} onChange={p.onAuto}/><div className="grid gap-4 sm:grid-cols-2"><div><div className="mb-2 text-center font-bold">DA INTAKE {p.intake.toFixed(1)}%</div><SpringLever label="DA INTAKE VALVE" negativeLabel="CLOSE" positiveLabel="OPEN" direction={p.intakeDirection} onDirectionChange={p.onIntakeDirection}/></div><div><div className="mb-2 text-center font-bold">DA OUTTAKE {p.outtake.toFixed(1)}%</div><SpringLever label="DA OUTTAKE VALVE" negativeLabel="CLOSE" positiveLabel="OPEN" direction={p.outtakeDirection} onDirectionChange={p.onOuttakeDirection}/></div></div><div className="flex justify-center"><SpringButton label={p.fastCloseHeld ? "FAST CLOSE ACTIVE" : "DA FAST CLOSE"} variant="danger" onHoldChange={p.onFastClose}/></div><p className="text-xs text-slate-400">Opening intake raises DA temperature and intake-air flow. Pressure holds when the two flows match; greater outtake lowers pressure and greater intake raises it. Neither valve commands MCC water flow.</p></CardContent></Card>
  <Card className={p.disk === "ruptured" ? "border-red-500/60 bg-red-950/20" : "border-slate-700 bg-slate-900/70"}><CardHeader><CardTitle className={p.disk === "ruptured" ? "text-red-200" : "text-slate-100"}>DA air-outlet rupture disk</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><MaintainedSwitch label="DA AIR BYPASS VALVE" on={p.bypassOpen} onChange={p.onBypass}/><MaintainedSwitch label="DA MAIN AIR VALVE" on={p.mainAirValveOpen} onChange={p.onMainAirValve}/><div className="rounded bg-slate-950 p-3 text-center"><small>DISK STATUS</small><strong className={`block ${p.disk === "intact" ? "text-emerald-300" : p.disk === "ruptured" ? "text-red-300" : "text-amber-300"}`}>{p.disk.toUpperCase()}</strong></div></div><div className="flex flex-wrap gap-3"><Button disabled={p.disk !== "ruptured" || !p.bypassOpen || p.mainAirValveOpen} onClick={p.onRemoveDisk}>TAKE APART / REMOVE DISK</Button><Button variant="outline" disabled={p.disk !== "removed"} onClick={p.onInstallDisk}>INSTALL REPLACEMENT DISK</Button><Button variant="outline" disabled={p.disk !== "replaced"} onClick={p.onRestore}>RESTORE MAIN AIR VALVE</Button></div><p className="text-xs text-slate-300">If the disk ruptures: first open the bypass valve, then close the main air valve. Remove and replace the disk, restore the main air valve, and only then close the bypass. The disk is on the DA air outlet, so MCC water flow continues throughout maintenance.</p></CardContent></Card>
</div>;
