import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { MaintainedSwitch } from "@/components/HardwareControls";

type Props = {
  busE: boolean; selected: "u2a" | "u2b"; onSelected: (value: "u2a" | "u2b") => void;
  auto: boolean; onAuto: (value: boolean) => void; ignition: boolean; onIgnition: (value: boolean) => void;
  output: boolean; onOutput: (value: boolean) => void; mainBreaker: boolean; onMainBreaker: (value: boolean) => void;
  startRequested: boolean; onStart: () => void; onTrip: () => void; rpm: number; tank: number; fuelA: number; fuelB: number;
  mainFuelValve: boolean; onMainFuelValve: (value: boolean) => void; mainFuelPump: boolean; onMainFuelPump: (value: boolean) => void;
  fuelValveA: boolean; onFuelValveA: (value: boolean) => void; fuelValveB: boolean; onFuelValveB: (value: boolean) => void;
  refuellingSeconds: number;
};

export const EdgBayPanel = (p: Props) => {
  const selectedFuel = p.selected === "u2a" ? p.fuelA : p.fuelB;
  const ready = p.ignition && selectedFuel > 1;
  return <div className="space-y-6">
    <Card className="border-emerald-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-emerald-200">EDG bay — separate emergency supply</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded bg-slate-950 p-4"><small>U1 EDG-1</small><strong className="block text-xl text-cyan-200">REFERENCE / READY</strong><span className="text-xs text-slate-400">Independent Unit 1 machine · infinite fuel</span></div><div className="rounded bg-slate-950 p-4"><small>U2 EDG SELECTED</small><strong className="block text-xl text-emerald-300">{p.selected === "u2a" ? "EDG-2A" : "EDG-2B"}</strong><span className="text-xs text-slate-400">{selectedFuel.toFixed(1)}% local fuel</span></div><div className="rounded bg-slate-950 p-4"><small>ENGINE SPEED</small><strong className={`block text-xl ${p.rpm >= 1790 ? "text-emerald-300" : "text-amber-300"}`}>{p.rpm.toFixed(0)} RPM</strong><span className="text-xs text-slate-400">{p.rpm >= 1790 ? "AVAILABLE" : p.startRequested ? "RUNNING UP" : "STOPPED"}</span></div></div><div className="grid gap-3 sm:grid-cols-4"><MaintainedSwitch label="EDG AUTO" on={p.auto} onChange={p.onAuto}/><MaintainedSwitch label="IGNITION BREAKER (BUS E)" on={p.ignition} unavailable={!p.busE} onChange={p.onIgnition}/><Button className="min-h-11" disabled={!ready || p.startRequested} onClick={p.onStart}>{p.startRequested ? "START REQUESTED" : "LOCAL START"}</Button><Button variant="destructive" className="min-h-11" disabled={!p.startRequested && p.rpm < 1} onClick={p.onTrip}>TRIP SELECTED EDG</Button></div><p className="text-xs text-slate-400">Trip stops the selected EDG and opens its output and Bus S main breakers. Re-establish the normal Bus A → Bus S feed manually if required.</p></CardContent></Card>
    <div className="grid gap-6 lg:grid-cols-2"><Card className="border-amber-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-amber-200">Unit 2 EDG output chain</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3"><Button variant={p.selected === "u2a" ? "default" : "outline"} onClick={() => p.onSelected("u2a")}>SELECT EDG-2A</Button><Button variant={p.selected === "u2b" ? "default" : "outline"} onClick={() => p.onSelected("u2b")}>SELECT EDG-2B</Button></div><MaintainedSwitch label="EDG OUTPUT BREAKER" on={p.output} disabled={p.rpm < 1790} onChange={p.onOutput}/><MaintainedSwitch label="EDG MAIN BREAKER → BUS S" on={p.mainBreaker} disabled={!p.output || p.rpm < 1790} onChange={p.onMainBreaker}/><p className="text-xs text-slate-400">Close ignition, start and reach 1,800 RPM; then close the output breaker and main breaker. Closing the EDG main breaker opens the Unit 2 Bus A → Bus S feed and supplies Bus S directly.</p></CardContent></Card><Card className="border-red-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-red-200">U2 diesel fuel system</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded bg-slate-950 p-3 text-center"><small>LOCAL STORAGE TANK</small><strong className="block text-3xl text-amber-200">{p.tank.toFixed(1)}%</strong>{p.refuellingSeconds > 0 && <span className="text-xs text-cyan-300">REFUELLING · {Math.ceil(p.refuellingSeconds)} s remaining</span>}</div><div className="grid grid-cols-2 gap-3"><MaintainedSwitch label="MAIN FUEL VALVE" on={p.mainFuelValve} onChange={p.onMainFuelValve}/><MaintainedSwitch label="MAIN FUEL PUMP" on={p.mainFuelPump} disabled={p.refuellingSeconds > 0} onChange={p.onMainFuelPump}/><MaintainedSwitch label="EDG-2A FUEL VALVE" on={p.fuelValveA} onChange={p.onFuelValveA}/><MaintainedSwitch label="EDG-2B FUEL VALVE" on={p.fuelValveB} onChange={p.onFuelValveB}/></div><p className="rounded border border-cyan-500/30 bg-cyan-950/20 p-3 text-sm text-cyan-100">When the local tank is empty, call <strong>0027</strong> and type <strong>REFUEL</strong>. The three-minute delivery locks the main fuel pump off while the tank fills.</p></CardContent></Card></div>
  </div>;
};
