import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MaintainedSwitch } from "@/components/HardwareControls";
import { Cable } from "lucide-react";
import type { ReactNode } from "react";

interface Props { startupBusA: boolean; turbineBusB: boolean; safetyBusS: boolean; rolldownProtection: boolean; turbineOnline: boolean; startupLoad?: number; busBLoad?: number; safetyLoad?: number; onStartupBusAChange: (value: boolean) => void; onTurbineBusBChange: (value: boolean) => void; onSafetyBusSChange: (value: boolean) => void; onRolldownProtectionChange: (value: boolean) => void; }

const Bus = ({ label, active, detail, children }: { label: string; active: boolean; detail: string; children: ReactNode }) => <div className={`rounded-xl border p-4 ${active ? "border-emerald-500/50 bg-emerald-950/20" : "border-slate-700 bg-slate-950/50"}`}><div className="mb-3 flex justify-between"><strong>{label}</strong><Badge className={active ? "bg-emerald-700" : "bg-slate-700"}>{active ? "ENERGIZED" : "DE-ENERGIZED"}</Badge></div><p className="mb-4 text-xs text-slate-400">{detail}</p>{children}</div>;

export const ElectricalPanel = ({ startupBusA, turbineBusB, safetyBusS, rolldownProtection, turbineOnline, startupLoad = 0, busBLoad = 0, safetyLoad = 0, onStartupBusAChange, onTurbineBusBChange, onSafetyBusSChange, onRolldownProtectionChange }: Props) => {
  const meter = (name: string, load: number, limit: number) => <div className="rounded bg-slate-950 p-3"><div className="mb-1 flex justify-between text-xs"><span>{name}</span><strong className={load > limit * .85 ? "text-amber-300" : "text-cyan-300"}>{load.toFixed(0)} / {limit} kW</strong></div><div className="h-2 overflow-hidden rounded bg-slate-800"><div className={load > limit ? "h-full bg-red-500" : load > limit * .85 ? "h-full bg-amber-400" : "h-full bg-cyan-400"} style={{ width: `${Math.min(100, load / limit * 100)}%` }}/></div></div>;
  return <div className="grid gap-6 lg:grid-cols-2"><Card className="border-yellow-500/30 bg-slate-900/70"><CardHeader><CardTitle className="flex gap-2 text-yellow-200"><Cable/>Electrical distribution</CardTitle></CardHeader><CardContent className="space-y-4"><Bus label="STARTUP TRANSFORMER / BUS A" active={startupBusA} detail="Initial plant and CRD auxiliary supply.">{meter("AVAILABLE CAPACITY", startupLoad, 30)}<div className="mt-3"><MaintainedSwitch label="BUS A BREAKER" on={startupBusA} onChange={onStartupBusAChange}/></div></Bus><Bus label="TURBINE GENERATOR / BUS B" active={turbineBusB && turbineOnline} detail="Generator output. Required for FWP 2/B availability.">{meter("AVAILABLE CAPACITY", busBLoad, 60)}<div className="mt-3"><MaintainedSwitch label="BUS B BREAKER" on={turbineBusB} onChange={onTurbineBusBChange}/></div></Bus><Bus label="SAFETY BUS S" active={safetyBusS} detail="CST and Hotwell pumps, RCIC and LPCI supply.">{meter("SAFETY LOAD", safetyLoad, 30)}<div className="mt-3"><MaintainedSwitch label="BUS S BREAKER" on={safetyBusS} onChange={onSafetyBusSChange}/></div></Bus></CardContent></Card><Card className="border-red-500/30 bg-slate-900/70"><CardHeader><CardTitle className="text-red-200">Generator protection</CardTitle></CardHeader><CardContent className="space-y-5"><div className="rounded-lg border border-red-500/30 bg-red-950/20 p-4"><div className="mb-2 flex justify-between"><strong>ROLLDOWN PROTECTION</strong><Badge className={rolldownProtection ? "bg-emerald-700" : "bg-red-700"}>{rolldownProtection ? "ENABLED" : "BYPASSED"}</Badge></div><p className="text-sm text-slate-400">RPS Channel B monitors turbine trips. Bypassing roll-down protection prevents Channel B from opening the grid breaker.</p><div className="mt-4"><MaintainedSwitch label="PROTECTION BREAKER" on={rolldownProtection} onChange={onRolldownProtectionChange}/></div></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded bg-slate-950 p-3"><small>FWP 2/B</small><br/><strong className={turbineBusB && turbineOnline ? "text-emerald-400" : "text-red-400"}>{turbineBusB && turbineOnline ? "AVAILABLE" : "NO BUS B"}</strong></div><div className="rounded bg-slate-950 p-3"><small>LPCI / RCIC</small><br/><strong className={safetyBusS ? "text-emerald-400" : "text-red-400"}>{safetyBusS ? "AVAILABLE" : "NO BUS S"}</strong></div></div></CardContent></Card></div>;
};
