import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MaintainedSwitch } from "@/components/HardwareControls";
import { Slider } from "@/components/ui/slider";

type PumpProps = {
  name: string;
  running: boolean;
  flow: number;
  cooling: number;
  preheat: boolean;
  motorTemperature: number;
  oilTemperature: number;
  onCooling: (value: number) => void;
  onPreheat: (value: boolean) => void;
};

type Props = {
  pumpA: PumpProps;
  pumpB: PumpProps;
  auto: boolean;
  onAuto: (value: boolean) => void;
};

const PumpTrain = ({ p, auto }: { p: PumpProps; auto: boolean }) => (
  <Card className="border-amber-500/30 bg-slate-900/70">
    <CardHeader><CardTitle className="text-amber-200">{p.name} motor auxiliary train</CardTitle></CardHeader>
    <CardContent className="space-y-4">
      <div className="grid grid-cols-3 gap-3 text-center text-sm">
        <div className="rounded bg-slate-950 p-3"><small>FLOW</small><strong className="block text-lg">{p.flow.toFixed(0)} kg/s</strong></div>
        <div className="rounded bg-slate-950 p-3"><small>MOTOR</small><strong className={`block text-lg ${p.motorTemperature > 85 ? "text-red-300" : "text-emerald-300"}`}>{p.motorTemperature.toFixed(0)} °C</strong></div>
        <div className="rounded bg-slate-950 p-3"><small>OIL</small><strong className={`block text-lg ${p.oilTemperature < 25 ? "text-amber-300" : "text-cyan-300"}`}>{p.oilTemperature.toFixed(0)} °C</strong></div>
      </div>
      <div>
        <div className="mb-2 flex justify-between text-sm font-bold"><span>MOTOR COOLING WATER</span><span>{p.cooling.toFixed(1)}%</span></div>
        <Slider value={[p.cooling]} max={100} step={0.1} disabled={auto} onValueChange={value => p.onCooling(value[0])}/>
        <p className="mt-2 text-xs text-slate-400">Cooling removes motor heat generated by feedwater-pump load. In AUTO, the bay regulates it from motor temperature.</p>
      </div>
      <MaintainedSwitch label="PUMP OIL PREHEAT" on={p.preheat} disabled={auto} onChange={p.onPreheat}/>
      <p className="text-xs text-slate-400">Oil preheat conditions a stopped pump for restart; it is normally removed once the pump has warmed and is carrying flow.</p>
    </CardContent>
  </Card>
);

export const FeedwaterPumpBayPanel = ({ pumpA, pumpB, auto, onAuto }: Props) => (
  <div className="space-y-6">
    <Card className="border-cyan-500/30 bg-slate-900/70"><CardContent className="flex flex-wrap items-center justify-between gap-3 py-4"><div><strong className="text-cyan-200">Feedwater pump bay control</strong><p className="text-xs text-slate-400">This station owns motor cooling, bearing-oil conditioning, and their automatic controller. Pump breakers and process flow remain MCC controls.</p></div><MaintainedSwitch label="FWP AUX AUTO" on={auto} onChange={onAuto}/></CardContent></Card>
    <div className="grid gap-6 xl:grid-cols-2"><PumpTrain p={pumpA} auto={auto}/><PumpTrain p={pumpB} auto={auto}/></div>
  </div>
);
