import { Power } from "lucide-react";
import type { ReactorMode } from "@/lib/rodProgram";

export const MaintainedSwitch = ({ label, on, onChange, disabled = false, unavailable = false, tooltip }: { label: string; on: boolean; onChange: (value: boolean) => void; disabled?: boolean; unavailable?: boolean; tooltip?: string }) => (
  <button type="button" data-tooltip-title={label} data-tooltip-description={tooltip ?? `Currently ${on ? "on" : "off"}. Select to turn it ${on ? "off" : "on"}.`} disabled={disabled} onClick={() => onChange(!on)} aria-pressed={on} className="group flex min-w-28 flex-col items-center gap-2 disabled:cursor-not-allowed disabled:opacity-50">
    <span className="text-[10px] font-bold tracking-widest text-slate-400">{label}</span>
    <span className={`relative h-14 w-8 rounded-md border-2 p-1 shadow-inner transition-colors ${on ? unavailable ? "border-amber-300 bg-amber-950" : "border-emerald-400 bg-emerald-950" : "border-slate-600 bg-slate-950"}`}>
      <span className={`block h-5 w-full rounded-sm shadow transition-transform ${on ? `translate-y-6 ${unavailable ? "bg-amber-300" : "bg-emerald-400"}` : "translate-y-0 bg-slate-400"}`} />
    </span>
    <span className={on ? unavailable ? "text-xs font-bold text-amber-300" : "text-xs font-bold text-emerald-400" : "text-xs font-bold text-slate-500"}>{on ? unavailable ? "NO POWER" : "ON" : "OFF"}</span>
  </button>
);

export const SpringLever = ({ label, negativeLabel, positiveLabel, direction, onDirectionChange, tooltip, extended = false, hideNeutral = false }: { label: string; negativeLabel: string; positiveLabel: string; direction: number; onDirectionChange: (direction: number) => void; tooltip?: string; extended?: boolean; hideNeutral?: boolean }) => {
  const noNeutral = hideNeutral || label === "IRM RANGE SELECTOR";
  const positions = extended ? [-2, -1, 0, 1, 2] : noNeutral ? [-1, 1] : [-1, 0, 1];
  const positionLabel = (position: number) => position === 0 ? "NEUTRAL" : position < 0 ? `${position === -2 ? "FAST " : ""}${negativeLabel}` : `${position === 2 ? "FAST " : ""}${positiveLabel}`;
  const instruction = tooltip ?? `${label}. Select a latched direction; select Neutral to stop movement.`;
  return <div className="rounded-xl border border-slate-700 bg-slate-950/60 p-3 text-center sm:p-4"><div className="mb-3 text-[10px] font-bold tracking-[.2em] text-slate-400">{label}</div><div className={`grid items-center gap-1 ${extended ? "grid-cols-5" : noNeutral ? "grid-cols-2" : "grid-cols-3"}`}>{positions.map(position => <button key={position} type="button" data-tooltip-title={`${label}: ${positionLabel(position)}`} data-tooltip-description={`${instruction} ${position === 0 ? "Stops the actuator." : `Moves ${positionLabel(position).toLowerCase()} until Neutral is selected.`}`} onClick={() => onDirectionChange(direction === position && position !== 0 ? 0 : position)} aria-pressed={direction === position} className={`min-h-12 touch-manipulation rounded-lg border px-1 py-2 text-[10px] font-black transition sm:text-xs ${direction === position ? position < 0 ? "border-red-300 bg-red-700 text-white" : position > 0 ? "border-emerald-300 bg-emerald-700 text-white" : "border-amber-200 bg-amber-400 text-slate-950" : "border-slate-600 bg-slate-800 text-slate-300 hover:bg-slate-700"}`}>{position === -2 ? "−−" : position === -1 ? "−" : position === 0 ? "N" : position === 1 ? "+" : "++"}<span className="mt-1 block text-[8px] font-medium opacity-80">{positionLabel(position)}</span></button>)}</div><p className="mt-3 text-[10px] text-slate-500">{noNeutral ? "PULSE SELECTOR · RETURNS AUTOMATICALLY" : "LATCHED POSITION · SELECT NEUTRAL TO STOP"}</p></div>;
};

export const SpringButton = ({ label, onClick, onHoldChange, variant = "default", disabled = false, tooltip }: { label: string; onClick?: () => void; onHoldChange?: (held: boolean) => void; variant?: "default" | "danger"; disabled?: boolean; tooltip?: string }) => {
  const release = () => onHoldChange?.(false);
  return <button type="button" data-tooltip-title={label} data-tooltip-description={tooltip ?? `${onHoldChange ? "Hold" : "Press"} to activate this control.`} disabled={disabled} onClick={onClick} onPointerDown={event => { if (!onHoldChange) return; event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); onHoldChange(true); }} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release} onKeyDown={event => { if (onHoldChange && (event.key === " " || event.key === "Enter")) onHoldChange(true); }} onKeyUp={release} onBlur={release} className={`inline-flex min-h-14 touch-manipulation items-center justify-center gap-2 rounded-full border-4 px-6 text-sm font-black shadow-[0_5px_0_rgba(0,0,0,.5)] transition active:translate-y-1 active:shadow-none disabled:opacity-40 ${variant === "danger" ? "border-red-950 bg-red-600 text-white" : "border-emerald-950 bg-emerald-500 text-slate-950"}`}><Power size={16}/>{label}</button>;
};

export const ModeSelector = ({ value, onChange }: { value: ReactorMode; onChange: (mode: ReactorMode) => void }) => { const tips: Record<ReactorMode, string> = { SD: "Shutdown: inserts and holds all rods.", SRM: "Source Range Monitor: permits the initial 5% withdrawal step.", IPR: "Intermediate Range Monitor: uses an eight-range meter while the programmed intermediate withdrawal window is active.", RUN: "Run: enables normal rod regulation after startup." }; return <div className="rounded-xl border border-slate-600 bg-gradient-to-b from-slate-700 to-slate-950 p-4 shadow-inner"><div className="mb-3 text-center text-[10px] font-bold tracking-[.22em] text-slate-300">REACTOR MODE</div><div className="grid grid-cols-4 gap-2">{(["SD", "SRM", "IPR", "RUN"] as ReactorMode[]).map(mode => <button key={mode} type="button" data-tooltip-title={mode === "IPR" ? "IRM" : mode} data-tooltip-description={tips[mode]} onClick={() => onChange(mode)} aria-pressed={value === mode} className={`rounded border px-2 py-3 text-xs font-black transition ${value === mode ? "border-amber-200 bg-amber-400 text-slate-950 shadow-[0_0_12px_rgba(251,191,36,.7)]" : "border-slate-600 bg-slate-900 text-slate-300 hover:bg-slate-800"}`}>{mode === "IPR" ? "IRM" : mode}</button>)}</div><div className="mt-3 h-1 rounded bg-slate-950"><div className="h-1 rounded bg-amber-300 transition-all" style={{ width: `${(["SD", "SRM", "IPR", "RUN"] as ReactorMode[]).indexOf(value) * 33.33 + 2}%` }} /></div></div>; };
