import { Activity, Fan, RadioTower, Waves } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Slider } from "@/components/ui/slider";
import { MaintainedSwitch } from "@/components/HardwareControls";

export type ProcessPanel = "condenser" | "feedwater" | "mcc" | "rps";
interface Props { panel: ProcessPanel; condenserVacuum: number; condenserPumpOn: boolean; condenserPumpB: boolean; condenserValve: number; busBAvailable: boolean; sjaeOn: boolean; deaeratorLevel: number; feedwaterDemand: number; mccLevel: number; mccPumpOn: boolean; rpsTrips: Record<string, boolean>; reactorLevel: number; hotwellLevel: number; condensateFlow: number; steamFlow: number; onCondenserPumpChange: (v: boolean) => void; onCondenserPumpBChange: (v: boolean) => void; onCondenserValveChange: (v: number) => void; onSjaeChange: (v: boolean) => void; onFeedwaterDemandChange: (v: number) => void; onCondensateFlowChange: (v: number) => void; onMccPumpChange: (v: boolean) => void; onManualTrip: () => void; onResetTrips: () => void; }
const Meter = ({ label, value, suffix = "%" }: { label: string; value: number; suffix?: string }) => <div><div className="mb-1 flex justify-between text-sm"><span className="text-slate-400">{label}</span><strong>{value.toFixed(1)}{suffix}</strong></div><Progress value={Math.max(0, Math.min(value, 100))} className="bg-slate-700"/></div>;

export const PlantSystemsPanel = (p: Props) => {
  if (p.panel === "condenser") return <div className="grid gap-6 lg:grid-cols-2"><Card className="border-sky-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-sky-300"><Fan/>Condenser controls</CardTitle></CardHeader><CardContent className="space-y-5"><div className="rounded-xl border border-sky-500/20 bg-slate-950/50 p-5 text-center"><div className="text-xs tracking-widest text-slate-400">CONDENSER VACUUM</div><div className="mt-2 text-5xl font-bold text-sky-300">{p.condenserVacuum.toFixed(0)} <span className="text-lg">%</span></div></div><div className="grid grid-cols-2 gap-4"><MaintainedSwitch label="CONDENSER PUMP A" on={p.condenserPumpOn} onChange={p.onCondenserPumpChange}/><MaintainedSwitch label="CONDENSER PUMP B" on={p.condenserPumpB} disabled={!p.busBAvailable} onChange={p.onCondenserPumpBChange}/></div><MaintainedSwitch label="STEAM JET AIR EJECTOR" on={p.sjaeOn} onChange={p.onSjaeChange}/><div><div className="mb-2 flex justify-between text-sm"><span>Condenser pressure control valve</span><strong>{p.condenserValve}%</strong></div><Slider value={[p.condenserValve]} max={100} onValueChange={v => p.onCondenserValveChange(v[0])}/></div></CardContent></Card><Card className="border-slate-700 bg-slate-900/60"><CardHeader><CardTitle>Condenser status</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex justify-between"><span>Pump B supply</span><Badge className={p.busBAvailable ? "bg-emerald-700" : "bg-red-700"}>{p.busBAvailable ? "BUS B AVAILABLE" : "NO BUS B"}</Badge></div><Meter label="Vacuum quality" value={p.condenserVacuum}/><p className="text-sm text-slate-400">The control valve regulates steam admission to the condenser train; closing it reduces achievable vacuum.</p></CardContent></Card></div>;
  if (p.panel === "feedwater") return <div className="grid gap-6 lg:grid-cols-2"><Card className="border-amber-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-amber-300"><Waves/>Deaerator / feedwater</CardTitle></CardHeader><CardContent className="space-y-5"><Meter label="DA level" value={5 + p.deaeratorLevel} suffix=" m"/><div><div className="mb-2 flex justify-between text-sm"><span>Feedwater demand</span><strong>{p.feedwaterDemand}%</strong></div><Slider value={[p.feedwaterDemand]} max={100} onValueChange={v => p.onFeedwaterDemandChange(v[0])}/></div></CardContent></Card></div>;
  if (p.panel === "mcc") return <div className="grid gap-6 lg:grid-cols-2"><Card className="border-blue-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-blue-300"><Activity/>MCC water inventory</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid grid-cols-3 gap-3">{[["REACTOR", p.reactorLevel], ["HOTWELL", p.hotwellLevel], ["DA", p.deaeratorLevel]].map(([label, level]) => <div key={label as string} className="rounded border border-slate-700 bg-slate-950/60 p-3 text-center"><div className="mx-auto mb-2 flex h-28 w-8 items-end overflow-hidden rounded border border-slate-500"><div className="w-full bg-cyan-400" style={{height: `${Math.max(0, Math.min(100, 50 + Number(level) * 10))}%`}}/></div><small>{label as string}</small><strong className="block">{(5 + Number(level)).toFixed(2)} m</strong></div>)}</div><MaintainedSwitch label="MCC CIRCULATION PUMP" on={p.mccPumpOn} onChange={p.onMccPumpChange}/></CardContent></Card><Card className="border-slate-700 bg-slate-900/60"><CardHeader><CardTitle>Transfer controls</CardTitle></CardHeader><CardContent className="space-y-5"><div><div className="mb-2 flex justify-between"><span>Hotwell transfer</span><strong>{p.condensateFlow}%</strong></div><Slider value={[p.condensateFlow]} max={100} onValueChange={v => p.onCondensateFlowChange(v[0])}/></div><div><div className="mb-2 flex justify-between"><span>Feedwater transfer</span><strong>{p.feedwaterDemand}%</strong></div><Slider value={[p.feedwaterDemand]} max={100} onValueChange={v => p.onFeedwaterDemandChange(v[0])}/></div><Meter label="MCC reserve" value={p.mccLevel}/></CardContent></Card></div>;
  return <Card className="border-red-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-red-300"><RadioTower/>Reactor Protection System</CardTitle></CardHeader><CardContent><div className="grid gap-2 md:grid-cols-2">{Object.entries(p.rpsTrips).map(([name, trip]) => <div key={name} className="flex justify-between rounded bg-slate-950 p-3"><span>{name}</span><strong className={trip ? "text-red-400" : "text-emerald-400"}>{trip ? "TRIP" : "CLEAR"}</strong></div>)}</div><div className="mt-4 flex gap-3"><Button onClick={p.onManualTrip}>MANUAL TRIP</Button><Button variant="outline" onClick={p.onResetTrips}>RESET NODES</Button></div></CardContent></Card>;
};
