import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Droplets } from "lucide-react";
import { PumpIcon } from "./PumpIcon";
import { MaintainedSwitch } from "@/components/HardwareControls";

interface Props { pump1Online: boolean; pump2Online: boolean; busBAvailable: boolean; daIntakeOpen: boolean; daOutputOpen: boolean; onPump1Change: (v: boolean) => void; onPump2Change: (v: boolean) => void; onDaIntakeChange: (v: boolean) => void; onDaOutputChange: (v: boolean) => void; }
export const PowerCoolantPanel: React.FC<Props> = p => <div className="grid gap-6 lg:grid-cols-2">
  <Card className="border-cyan-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-cyan-300"><Droplets/>CRD cooling / feedwater pumps</CardTitle></CardHeader><CardContent className="space-y-4">{[["FWP 1 / A", p.pump1Online, p.onPump1Change, true], ["FWP 2 / B", p.pump2Online, p.onPump2Change, p.busBAvailable]].map(([label, on, change, available]) => <div key={label as string} className="flex items-center justify-between rounded border border-slate-700 bg-slate-950/50 p-4"><div className="flex items-center gap-3"><PumpIcon isOnline={Boolean(on)}/><div><strong>{label as string}</strong><p className="text-xs text-slate-400">{available ? "AVAILABLE" : "BUS B REQUIRED"}</p></div></div><MaintainedSwitch label="BREAKER" on={Boolean(on)} disabled={!available} onChange={change as (value: boolean) => void}/></div>)}<Badge className={(p.pump1Online || p.pump2Online) ? "bg-emerald-700" : "bg-slate-700"}>{p.pump1Online || p.pump2Online ? "FEEDWATER / CRD COOLING AVAILABLE" : "NO FEEDWATER PUMP"}</Badge></CardContent></Card>
  <Card className="border-amber-500/30 bg-slate-900/60"><CardHeader><CardTitle className="text-amber-300">Deaerator flow path</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm text-slate-400">Closing either valve bypasses the DA, allowing direct MCC transfer around the vessel.</p><div className="grid grid-cols-2 gap-5"><MaintainedSwitch label="DA INTAKE VALVE" on={p.daIntakeOpen} onChange={p.onDaIntakeChange}/><MaintainedSwitch label="DA OUTPUT VALVE" on={p.daOutputOpen} onChange={p.onDaOutputChange}/></div><div className="rounded bg-slate-950 p-4 text-sm">Path: <strong className={p.daIntakeOpen && p.daOutputOpen ? "text-emerald-400" : "text-amber-300"}>{p.daIntakeOpen && p.daOutputOpen ? "HOTWELL → DA → FWP" : "DA BYPASS ACTIVE"}</strong></div></CardContent></Card>
</div>;
