import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Droplets } from "lucide-react";
import { PumpIcon } from "./PumpIcon";
import { MaintainedSwitch, SpringLever } from "@/components/HardwareControls";

interface Props { pump1Online: boolean; pump2Online: boolean; busBAvailable: boolean; daIntakeOpen: boolean; daOutputOpen: boolean; daIntakeValve?: number; daOuttakeValve?: number; daTemperature?: number; daPressure?: number; daIntakeDirection?: number; daOuttakeDirection?: number; onPump1Change: (v: boolean) => void; onPump2Change: (v: boolean) => void; onDaIntakeChange: (v: boolean) => void; onDaOutputChange: (v: boolean) => void; onDaIntakeValveChange?: (v: number) => void; onDaOuttakeValveChange?: (v: number) => void; onDaIntakeDirectionChange?: (v: number) => void; onDaOuttakeDirectionChange?: (v: number) => void; }
export const PowerCoolantPanel: React.FC<Props> = p => <div className="grid gap-6 lg:grid-cols-2"><Card className="border-cyan-500/30 bg-slate-900/60"><CardHeader><CardTitle className="flex gap-2 text-cyan-300"><Droplets/>CRD cooling / feedwater pumps</CardTitle></CardHeader><CardContent className="space-y-4">{[["FWP 1 / A",p.pump1Online,p.onPump1Change,true],["FWP 2 / B",p.pump2Online,p.onPump2Change,p.busBAvailable]].map(([label,on,change,available]) => <div key={label as string} className="flex items-center justify-between rounded border border-slate-700 bg-slate-950/50 p-4"><div className="flex items-center gap-3"><PumpIcon isOnline={Boolean(on)}/><strong>{label as string}</strong></div><MaintainedSwitch label="BREAKER" on={Boolean(on)} disabled={!available} onChange={change as (v:boolean)=>void}/></div>)}<Badge className={(p.pump1Online||p.pump2Online)?"bg-emerald-700":"bg-slate-700"}>{p.pump1Online||p.pump2Online?"FEEDWATER AVAILABLE":"NO FEEDWATER PUMP"}</Badge></CardContent></Card><Card className="border-amber-500/30 bg-slate-900/60"><CardHeader><CardTitle className="text-amber-300">Deaerator control</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-2"><div><div className="mb-2 text-center font-bold">DA INTAKE {p.daIntakeValve ?? 100}%</div><SpringLever label="DA INTAKE VALVE" negativeLabel="CLOSE" positiveLabel="OPEN" direction={p.daIntakeDirection ?? 0} onDirectionChange={value => p.onDaIntakeDirectionChange?.(value)}/></div><div><div className="mb-2 text-center font-bold">DA OUTTAKE {p.daOuttakeValve ?? 100}%</div><SpringLever label="DA OUTTAKE VALVE" negativeLabel="CLOSE" positiveLabel="OPEN" direction={p.daOuttakeDirection ?? 0} onDirectionChange={value => p.onDaOuttakeDirectionChange?.(value)}/></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded bg-slate-950 p-3">TEMP<strong className="block text-xl">{(p.daTemperature ?? 110).toFixed(1)}°C</strong></div><div className="rounded bg-slate-950 p-3">PRESSURE<strong className="block text-xl">{(p.daPressure ?? 1.5).toFixed(2)} bar</strong></div></div><p className="text-xs text-slate-400">These valves tune DA conditions only; MCC DA-outflow kg/s remains controlled by feedwater pumps.</p></CardContent></Card></div>;
