import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MaintainedSwitch } from "@/components/HardwareControls";
import { Badge } from "@/components/ui/badge";
import { Droplets, ShieldPlus } from "lucide-react";

interface WaterProps { cstLevel: number; hotwellLevel: number; cstMakeup: boolean; cstDrain: boolean; hotwellMakeup: boolean; hotwellDrain: boolean; busS: boolean; onCstMakeup: (v: boolean) => void; onCstDrain: (v: boolean) => void; onHotwellMakeup: (v: boolean) => void; onHotwellDrain: (v: boolean) => void; }
export const WaterManagementPanel = (p: WaterProps) => <div className="grid gap-6 lg:grid-cols-2"><Card className="border-cyan-500/30 bg-slate-900/70"><CardHeader><CardTitle className="flex gap-2 text-cyan-200"><Droplets/>CST / Hotwell management</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded bg-slate-950 p-4"><small>CST LEVEL</small><strong className="block text-3xl">{(p.cstLevel / 10).toFixed(2)} m</strong></div><div className="rounded bg-slate-950 p-4"><small>HOTWELL LEVEL</small><strong className="block text-3xl">{(5 + p.hotwellLevel).toFixed(2)} m</strong></div></div><p className="text-xs text-slate-400">All makeup and drain pumps require Safety Bus S and impose transformer load.</p><div className="grid grid-cols-2 gap-4"><MaintainedSwitch label="CST MAKEUP (15 kW)" on={p.cstMakeup} onChange={p.onCstMakeup} disabled={!p.busS}/><MaintainedSwitch label="CST DRAIN (15 kW)" on={p.cstDrain} onChange={p.onCstDrain} disabled={!p.busS}/><MaintainedSwitch label="HOTWELL MAKEUP (10 kW)" on={p.hotwellMakeup} onChange={p.onHotwellMakeup} disabled={!p.busS}/><MaintainedSwitch label="HOTWELL DRAIN (10 kW)" on={p.hotwellDrain} onChange={p.onHotwellDrain} disabled={!p.busS}/></div></CardContent></Card><Card className="border-slate-700 bg-slate-900/70"><CardHeader><CardTitle>Safety-bus interlock</CardTitle></CardHeader><CardContent><Badge className={p.busS ? "bg-emerald-700" : "bg-red-700"}>{p.busS ? "BUS S AVAILABLE" : "BUS S REQUIRED"}</Badge></CardContent></Card></div>;

interface SafetyProps { pressure: number; reactorLevel: number; busS: boolean; rcicValve: boolean; rcicPump: boolean; lpciPump: boolean; onRcicValve: (v: boolean) => void; onRcicPump: (v: boolean) => void; onLpciPump: (v: boolean) => void; }
export const SafetySystemsPanel = (p: SafetyProps) => { const rcicReady = p.busS && p.rcicValve && p.rcicPump && p.pressure < 3500; const lpciReady = p.busS && p.lpciPump && p.pressure >= 3500; return <div className="grid gap-6 lg:grid-cols-2"><Card className="border-red-500/30 bg-slate-900/70"><CardHeader><CardTitle className="flex gap-2 text-red-200"><ShieldPlus/>RCIC / LPCI</CardTitle></CardHeader><CardContent className="space-y-5"><div className="rounded border border-slate-700 p-4"><strong>RCIC — below 3500 kPa</strong><p className="my-2 text-xs text-slate-400">Isolates reactor water from other sources and injects via its turbopump.</p><div className="flex flex-wrap gap-5"><MaintainedSwitch label="ISOLATION VALVE" on={p.rcicValve} onChange={p.onRcicValve} disabled={!p.busS}/><MaintainedSwitch label="TURBOPUMP BREAKER" on={p.rcicPump} onChange={p.onRcicPump} disabled={!p.busS}/></div><Badge className={rcicReady ? "mt-3 bg-emerald-700" : "mt-3 bg-slate-700"}>{rcicReady ? "INJECTING" : "STANDBY / BLOCKED"}</Badge></div><div className="rounded border border-slate-700 p-4"><strong>LPCI — above 3500 kPa</strong><p className="my-2 text-xs text-slate-400">Injects water into the reactor without isolating other water paths.</p><MaintainedSwitch label="LPCI PUMP BREAKER" on={p.lpciPump} onChange={p.onLpciPump} disabled={!p.busS}/><Badge className={lpciReady ? "mt-3 bg-emerald-700" : "mt-3 bg-slate-700"}>{lpciReady ? "INJECTING" : "STANDBY / BLOCKED"}</Badge></div></CardContent></Card><Card className="border-slate-700 bg-slate-900/70"><CardHeader><CardTitle>Injection status</CardTitle></CardHeader><CardContent className="space-y-3"><div>RPV pressure: <strong>{p.pressure.toFixed(0)} kPa</strong></div><div>Reactor level: <strong>{(5 + p.reactorLevel).toFixed(2)} m</strong></div><div className={p.busS ? "text-emerald-400" : "text-red-400"}>Safety Bus S: {p.busS ? "AVAILABLE" : "UNAVAILABLE"}</div></CardContent></Card></div>; };
